### ISSUE TITLE
Error upon first start

### ISSUE THREAD

**Issue by xBounceIT** [haq/microsoft-rewards-bot#20]
I copied the wg0.conf and docker compose and added my own account.json but getting this error upon first start of the rewards_home:

ERROR:root:
Traceback (most recent call last):
  File "/app/main.py", line 39, in main
    earned_points = executeBot(currentAccount, args)
  File "/app/main.py", line 234, in executeBot
    with Browser(mobile=False, account=currentAccount, args=args) as desktopBrowser:
         ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/browser.py", line 41, in __init__
    self.localeLang, self.localeGeo = self.getLanguageCountry(args.lang, args.geo)
                                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/browser.py", line 234, in getLanguageCountry
    ).alpha_2
      ^^^^^^^
AttributeError: 'NoneType' object has no attribute 'alpha_2'

**Comment by d4k0** [comment]
I have just come across the same error. How can I set the language with docker compose? I have tried different variants, but nothing has worked so far.

**Comment by haq** [comment]
> I have just come across the same error. How can I set the language with docker compose? I have tried different variants, but nothing has worked so far.

```yml
rewards-home:
  image: ghcr.io/haq/microsoft-rewards-bot
  container_name: rewards_home
  command: python3 main.py --visible --lang en
  shm_size: 4gb
  volumes:
    - ./accounts.json:/app/accounts.json
  restart: no
```

You can find all launch arguments here: https://github.com/klept0/MS-Rewards-Farmer/tree/develop?tab=readme-ov-file#launch-arguments.
